# define the benchmarking settings

OPERATOR_BENCHMARK:
  n_samples: 1008  # samples to calculate expected value
  n_runs: 50  # number of runs to average performance
  lattice_size: 5 # extend of the lattice (same in every direction), details depend on how the operator is defined